config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :enrollments
  resources :subjects
  resources :instructors
  resources :courses
  get 'admin' => 'admin#index' 
  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    get 'logout' => :destroy
  end
  get 'admin/index'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  root 'users#new'

end

app/models/search.rb
class Search < ActiveRecord::Base


	def self.search(subject_var, course_var)
		# if subject_var == nil && course_var == nil
		# else
			convert = subject_var.to_s
			only_id_array = convert.split(' ')
			only_id = only_id_array[0]
			courses = Course.all
			courses = courses.where("name LIKE ?", "%#{course_var}%")
			courses = courses.where("subject LIKE ?", "%#{only_id}%")
		# end

	end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @subjects = Subject.all
    @subject_names = Array.new
    @subjects.each do |x|
      id_name = x.sub_id + " " + x.name
      @subject_names.push(id_name)
    end
    @searches = Search.search(params[:subject], params[:q])

    # respond_to do |format|
    #   format.js
    # end

  end

  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.fetch(:search, {})
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_course_results.html.erb
<h3>Search Results</h3>

<%if @searches.nil? || @searches.length == 0%>
	<p>No Matches Found</p>
<% else %>
	<p><%= @searches.length %> matches found</p>
	<%= render "form" %>
<% end %>

app/views/searches/_form.html.erb
<table class="table">
  
  <tbody>
    <% @searches.each do |course| %>
      <tr>
        <ul><%=course.name%>
        <%= link_to 'Enroll', new_enrollment_path(:course_var => course.id), :class => "button"%></ul>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<p id="notice"><%= notice %></p>

<div>
<h1>Listing Searches</h1>

<%= form_tag searches_path, :method => 'get', remote: true, :id => "course_search" do %>
  <p>
    <%= select_tag :subject, options_for_select(@subject_names), :include_blank => true, data: {
    	remote: true,
    	url: url_for(searches_path)
    } %>
    <%= label_tag(:q, "Course") %>
    <%= text_field_tag (:q) %>

    <%= submit_tag "Search", class: "btn btn-default"  %>
  </p>
<%end%>
</div>

<div id="course_results"></div>

app/views/searches/index.js.erb
$('#course_results').html("<%= escape_javascript (render(partial: 'course_results')) %>");

app/views/searches/new.html.erb
<h1>New Search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>