config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :enrollments
  resources :subjects
  resources :instructors
  resources :courses
  get 'admin' => 'admin#index' 
  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    get 'logout' => :destroy
  end
  get 'admin/index'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  root 'users#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CourseCatalog</title>
  <script src="http://js.pusher.com/2.1/pusher.min.js" type="text/javascript"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <script src="https://code.jquery.com/jquery.js" type="text/javascript"></script>


</head>
<body>

	<nav class="navbar navbar-default">
		<div class="container-fluid">

			<div class="navbar-header">
				<a href="#" class="navbar-brand">RAILS PA</a>
			</div>
			<!-- menu items -->
			<div>
				<ul class="nav navbar-nav">
					<% if session[:user_id].nil? %>
                    	 <li><%= link_to 'Home', login_path %></li>
          			<% else %>
            			<li><%= link_to 'Home', user_path(id: session[:user_id]) %></li>
          			<% end %>
					<li><%= link_to 'Courses', courses_url %></li>
					<li><%= link_to 'Instructors', instructors_url %></li>
					<li><%= link_to 'Subjects', subjects_url %></li>
					<li><%= link_to 'Search', searches_url %></li>


				</ul>
				<ul class="nav navbar-nav navbar-right">
		          <% if !session[:user_id].nil? %>
            		<li><button type="button" onclick="location.href = '/logout';" class="btn btn-default navbar-btn">Logout</button></li>
		          <% else %>
		            <li><button type="button" onclick="location.href = '/login';" class="btn btn-default navbar-btn">Login</button></li>
		          <% end %>
		        </ul>
			</div>


		</div>

	</nav>

<%= yield %>

</body>
</html>